import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import newStyles from '../styles/about.css'

export default function Home(){
  return (
    <div className={styles.container}>

    <Head>
    <title>Device Cure</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href = "/favicon.ico"/>
    </Head>

    <nav className={styles.mainnav}>
    <ul>
    <li>Home</li>
    <li>Home</li>
    <li>Home</li>
    <li>Home</li>
    </ul>
    </nav>

    <main className={styles.main}>
    
     <div className={styles.gridContainer}>
     <div className={styles.gridItem}>
     <Image src="/how_it_work.png" height="550" width="400"  alt="Screen Protection"/>
     </div>

     <div className="grid grid-cols-1 gap-10 content-center ...">
    
     <div >
     <p className={styles.itemHead}>Why <mark className={styles.particlaurWord}>DeviceCure</mark></p>

     <div class="grid grid-cols-2 gap-1">

     <div class="flex items-center pt-3">
     
     <Image class="flex justify-center items-center rounded-full border" className={styles.gridImage}  src="/image 8.webp" height="50" width = "70" />

     <div class="ml-4">
       <p className={styles.gridService}>DoorStep Service</p>
       <p className={styles.gridServicePara}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique quos</p>
     </div>
   </div>
   <div class="flex items-center pt-3">
   <Image class="flex justify-center items-center rounded-full border" className={styles.gridImage}  src="/image 8.webp" height="50" width = "70" />

   <div class="ml-4">
     <p className={styles.gridService}>Screen Replacement</p>
     <p className={styles.gridServicePara}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique quos</p>
   </div>
 </div>
     </div>
     </div>


     <div>
     <p className={styles.itemHead}>What's Not <mark className={styles.particlaurWord}>Covered</mark></p>

     <div class="grid grid-cols-2 gap-1">

     <div class="flex items-center pt-3">
     <Image class="flex justify-center items-center rounded-full border" className={styles.gridImage} src="/image 9-1.webp" height="50" width = "70" />

     <div class="ml-4">
       <p className={styles.gridService}>Theft Or Lost</p>
       <p className={styles.gridServicePara}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique quos</p>
     </div>
   </div>
   <div class="flex items-center pt-3">
   <Image class="flex justify-center items-center rounded-full border" className={styles.gridImage} src="/image 9.webp" height="50" width = "70" />

   <div class="ml-4">
     <p className={styles.gridService}>Unauthorised Repair</p>
     <p className={styles.gridServicePara}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique quos</p>
   </div>
 </div>
     </div>
     </div>
     <div>
     <button className={styles.gridItemButton}>See Details →</button></div>
     

     </div>
     </div>
   
     </main>

     <span style={{ backgroundImage : "url('/Other.png')"}}>
    </span>
    <section className= {styles.section} >
    
    <div className={styles.sectionContainer}>
 
    <div className={styles.footerSection}>
      <ul>
      <li className='mb-10'><Image src="/logoFooter.png" height="69" width="411"/></li>
      <p className={styles.footerHeads}>Reach Us</p>
      
      <p className='pt-10 pb-10'>21,22 Ganpati Vihar Colony, Rakdi, Sodala, Jaipur, Rajasthan - 302006</p>
      
      <p className={styles.footerHeads}>Follow us On</p>
     
      <li>
      
      <div class="flex mt-6 mb-6 ">
      <a href="#!" class="mr-6  text-gray-600">
      <div className={styles.users}  style={{ backgroundImage : "url('/facebook.png')" }}></div>
      </a>
      <a href="#!" class="mr-6  text-gray-600">
      <div className={styles.users}  style={{ backgroundImage : "url('/instagram.png')" }}></div>
      </a>
      <a href="#!" class="mr-6  text-gray-600">
      <div className={styles.users}  style={{ backgroundImage : "url('/twitter.png')" }}></div>
      </a>
      
      
      </div>
      </li>
      
      <li className='mb-10'>
      <p className={styles.footerHeads}>Download our app
      </p>
      </li>

      <div class="flex ml-0">
      <a href="#!" class=" text-gray-600">

      <Image  src="/playstore.png" height="125" width="382"/>
      </a>
      </div>
      </ul>
    </div>
    
   
    <div className={styles.footerSection}>
    <ul>
    <li className='mb-10'>
    <p className={styles.footerHeads}>Learn More</p>
    </li>
    <a href="#!">
    <li>About Us </li>
    </a>
    <a href="#!">
    <li>Blogs</li>
    </a>
    <a href="#!">
   <li>Contact Us</li>
   </a>
   <a href="#!">
   <li>Career</li>
   </a>
   <a href="#!">
   <li>Franchise</li>
   </a>
   <a href="#!">
      <li>Accessories</li>
      </a>
      <a href="#!">
   <li>Screen Protection</li>
   </a>
    </ul>
  </div>


  
     <div  className={styles.footerSection}>
      <ul>
      <li className='mb-10'>
      <p className={styles.footerHeads}>Important Links</p>
      </li>
      <a href="#!">
      <li>Privacy Policy</li>
      </a>
      <a href="#!">
      <li>Warranty Policy</li>
      </a>
      <a href="#!">
      <li>Terms & Conditons</li>
      </a>
      <a href="#!">
      <li>Warranty Claim</li>
      </a>
      <a href="#!">
     <li>Refer & Earn</li>
     </a>
   
      </ul>
    </div>

  </div>
    </section>
    </div>
    


  )
}